version: '3.3'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rootdb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rdr00tdb}
      POSTGRES_DB: ghostdb
    restart: always
    volumes:
      - type: bind
        source: ~/host-vol/postgresql-data
        target: /var/lib/postgresql/data

  ghost:
    image: ghost
    environment:
      database_url: postgres://rootdb:P@ssw0rdr00tdb@postgresql:5432/ghostdb
      mail__transport: ${MAIL_TRANSPORT:-Direct}
      mail__options__service: ${MAIL_SERVICE}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT:-25}
      mail__options__secureConnection: ${MAIL_SECURE:-false}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
    depends_on:
      - postgresql
    restart: always
    volumes:
      - type: bind
        source: ~/host-vol/ghost-data
        target: /var/lib/ghost/content

  nginx:
    image: nginx
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - type: bind
        source: ~/host-vol/nginx-webservices
        target: /etc/nginx/conf.d/

