version: '3.3'

services:
  postgresql:
    image: postgres
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root1234}
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ghost1234}
      MYSQL_DATABASE: ghost_production
    restart: always
    volumes:
      - type: bind
        source: ${MYSQL_HOST_PATH=-~/postgresql-data}
        target: /var/lib/mysql

  ghost-production:
    image: ghost:${GHOST_IMAGE_TAG:-latest}
    environment:
      database__client: mysql
      database__connection__host: postgresql
      database__connection__database: ghost_production
      database__connection__user: ghost
      database__connection__password: ${MYSQL_PASSWORD:-ghost1234}
      mail__transport: ${MAIL_TRANSPORT:-Direct}
      mail__options__service: ${MAIL_SERVICE}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT:-25}
      mail__options__secureConnection: ${MAIL_SECURE:-false}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
    depends_on:
      - postgresql
    restart: always
    volumes:
      - type: bind
        source: ${GHOST_HOST_PATH:-~/ghost-data}
        target: /var/lib/ghost/content

  nginx-webservices:
    image: nginx
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - type: bind
        source: ${NGINX_HOST_PATH:-~/nginx-webservices}
        target: /etc/nginx/conf.d/

